import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // docs/ 디렉터리 구조에서 사이드바를 자동 생성한다.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
